zenodo_accessrequests/views/requests.py
# -*- coding: utf-8 -*-
#
# This file is part of Zenodo.
# Copyright (C) 2015, 2016 CERN.
#
# Zenodo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Zenodo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zenodo. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

"""Views for creating access requests and sending access restricted files."""

from __future__ import absolute_import, print_function

from datetime import datetime

from flask import Blueprint, abort, current_app, flash, redirect, \
    render_template, request, url_for
from flask_babelex import gettext as _
from flask_login import current_user
from invenio_db import db
from werkzeug.local import LocalProxy

from ..forms import AccessRequestForm
from ..models import AccessRequest, RequestStatus
from ..tokens import EmailConfirmationSerializer

blueprint = Blueprint(
    'zenodo_accessrequests',
    __name__,
    url_prefix="/record",
    static_folder="../static",
    template_folder="../templates",
)


#
# Template filters
#


@blueprint.app_template_filter(name="is_restricted")
def is_restricted(record):
    """Template filter to check if a record is restricted."""
    return record.get('access_right') == 'restricted' and \
        record.get('access_conditions') and \
        record.get('owners', [])


@blueprint.app_template_filter()
def is_embargoed(record):
    """Template filter to check if a record is embargoed."""
    return record.get('access_right') == 'embargoed' and \
        record.get('embargo_date') and \
        record.get('embargo_date') > datetime.utcnow().date()


@blueprint.app_template_filter()
def is_removed(record):
    """Template filter to check if a record is removed."""
    return {'primary': 'SPAM'} in record.get('collections', [])

#
# Views
#


def access_request(pid, record, template, **kwargs):
    """Create an access request."""
    recid = int(pid.pid_value)
    datastore = LocalProxy(
        lambda: current_app.extensions['security'].datastore)

    # Record must be in restricted access mode.
    if record.get('access_right') != 'restricted' or \
       not record.get('access_conditions'):
        abort(404)

    # Record must have an owner and owner must still exists.
    owners = record.get('owners', [])
    record_owners = [datastore.find_user(id=owner_id) for owner_id in owners]
    if not record_owners:
        abort(404)

    sender = None
    initialdata = dict()

    # Prepare initial form data
    if current_user.is_authenticated:
        sender = current_user
        initialdata['email'] = current_user.email
        if current_user.profile:
            initialdata['full_name'] = current_user.profile.full_name

    # Normal form validation
    form = AccessRequestForm(formdata=request.form, **initialdata)

    if form.validate_on_submit():
        accreq = AccessRequest.create(
            recid=recid,
            receiver=record_owners[0],
            sender_full_name=form.data['full_name'],
            sender_email=form.data['email'],
            justification=form.data['justification'],
            sender=sender
        )
        db.session.commit()

        if accreq.status == RequestStatus.EMAIL_VALIDATION:
            flash(_(
                "Email confirmation needed: We have sent you an email to "
                "verify your address. Please check the email and follow the "
                "instructions to complete the access request."),
                category='info')
        else:
            flash(_("Access request submitted."), category='info')
        return redirect(url_for('invenio_records_ui.recid', pid_value=recid))

    return render_template(
        template,
        pid=pid,
        record=record,
        form=form,
        owners=record_owners,
    )


def confirm(pid, record, template, **kwargs):
    """Confirm email address."""
    recid = int(pid.pid_value)

    token = request.view_args['token']

    # Validate token
    data = EmailConfirmationSerializer.compat_validate_token(token)
    if data is None:
        flash(_("Invalid confirmation link."), category='danger')
        return redirect(url_for("invenio_records_ui.recid", pid_value=recid))

    # Validate request exists.
    r = AccessRequest.query.get(data['id'])
    if not r:
        abort(404)

    # Confirm email address.
    if r.status != RequestStatus.EMAIL_VALIDATION:
        if r.status == RequestStatus.PENDING:
            abort(
                400, 
                (
                    "Your email address has been verified. The access request "
                    "is now pending a decision from the record owner."
                )
            )
        else:
            abort(
                400, 
                (
                    "The request has been {}. "
                    "Check your mail inbox for the record owner's response."
                ).format(r.status.value.lower())
            )

    r.confirm_email()
    db.session.commit()
    flash(_("Email validated and access request submitted."), category='info')

    return redirect(url_for("invenio_records_ui.recid", pid_value=recid))

zenodo_accessrequests/views/settings.py
# -*- coding: utf-8 -*-
#
# This file is part of Zenodo.
# Copyright (C) 2015, 2016 CERN.
#
# Zenodo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Zenodo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zenodo. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

"""Accounts settings views for pending access requests and shared links."""

from __future__ import absolute_import, print_function

import re

from flask import Blueprint, abort, flash, redirect, render_template, \
    request, url_for
from flask_babelex import gettext as _
from flask_breadcrumbs import register_breadcrumb
from flask_login import current_user, login_required
from flask_menu import register_menu
from invenio_db import db
from jinja2 import Markup, escape, evalcontextfilter

from ..forms import ApprovalForm, DeleteForm
from ..helpers import QueryOrdering
from ..models import AccessRequest, RequestStatus, SecretLink
from ..utils import get_record

blueprint = Blueprint(
    'zenodo_accessrequests_settings',
    __name__,
    url_prefix="/account/settings/sharedlinks",
    static_folder="../static",
    template_folder="../templates",
)


_paragraph_re = re.compile(r'(?:\r\n|\r|\n){2,}')


@blueprint.app_template_filter()
@evalcontextfilter
def nl2br(eval_ctx, value):
    """Template filter to convert newlines to <br>-tags."""
    result = u'\n\n'.join(u'<p>%s</p>' % p.replace('\n', '<br>\n')
                          for p in _paragraph_re.split(escape(value)))
    if eval_ctx.autoescape:
        result = Markup(result)
    return result


@blueprint.route("/", methods=['GET', 'POST'])
@login_required
@register_menu(
    blueprint, 'settings.sharedlinks',
    _('%(icon)s Shared links', icon='<i class="fa fa-share fa-fw"></i>'),
    order=9,
    active_when=lambda: request.endpoint.startswith(
        "zenodo_accessrequests_settings.")
)
@register_breadcrumb(
    blueprint, 'breadcrumbs.settings.sharedlinks', _('Shared links')
)
def index():
    """List pending access requests and shared links."""
    query = request.args.get('query', '')
    order = request.args.get('sort', '-created')
    try:
        page = int(request.args.get('page', 1))
        per_page = int(request.args.get('per_page', 20))
    except (TypeError, ValueError):
        abort(404)

    # Delete form
    form = DeleteForm(request.form)
    if form.validate_on_submit():
        link = SecretLink.query_by_owner(current_user).filter_by(
            id=form.link.data).first()
        if link.revoke():
            flash(_("Shared link revoked."), category='success')
        db.session.commit()

    # Links
    links = SecretLink.query_by_owner(current_user).filter(
        SecretLink.revoked_at.is_(None)
    )

    # Querying
    if query:
        lquery = "%{0}%".format(query)
        links = links.filter(
            SecretLink.title.like(lquery) | SecretLink.description.like(lquery)
        )

    # Ordering
    ordering = QueryOrdering(links, ['title', 'created', 'expires_at'], order)
    links = ordering.items()

    # Pending access requests
    requests = AccessRequest.query_by_receiver(current_user).filter_by(
        status=RequestStatus.PENDING).order_by('created')

    return render_template(
        "zenodo_accessrequests/settings/index.html",
        links_pagination=links.paginate(page, per_page=per_page),
        requests=requests,
        query=query,
        order=ordering,
        get_record=get_record,
        form=DeleteForm(),
    )


@blueprint.route("/accessrequest/<int:request_id>/", methods=['GET', 'POST'])
@login_required
@register_breadcrumb(
    blueprint, 'breadcrumbs.settings.sharedlinks.accessrequest',
    _('Access request')
)
def accessrequest(request_id):
    """Accept/reject access request."""
    r = AccessRequest.get_by_receiver(request_id, current_user)
    if not r:
        abort(404)

    if r.status != RequestStatus.PENDING:
        abort(
            400, 
            (
                "This link is not available anymore since the access "
                "request has been {}. You can navigate to your "
                "\"Shared links\" page to see all your links."
            ).format(r.status.value.lower()),
        )

    form = ApprovalForm(request.form)

    if form.validate_on_submit():
        if form.accept.data:
            r.accept(message=form.data['message'],
                     expires_at=form.expires_at.data)
            db.session.commit()
            flash(_("Request accepted."))
            return redirect(url_for(".index"))
        elif form.reject.data:
            r.reject(message=form.data['message'])
            db.session.commit()
            flash(_("Request rejected."))
            return redirect(url_for(".index"))

    pid, record = get_record(r.recid)
    return render_template(
        "zenodo_accessrequests/settings/request.html",
        accessrequest=r,
        record=record,
        form=form,
    )

zenodo_accessrequests/templates/zenodo_accessrequests/settings/base.html
{#
## This file is part of Zenodo.
## Copyright (C) 2015, 2016 CERN.
##
## Zenodo is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## Zenodo is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Zenodo. If not, see <http://www.gnu.org/licenses/>.
##
## In applying this licence, CERN does not waive the privileges and immunities
## granted to it by virtue of its status as an Intergovernmental Organization
## or submit itself to any jurisdiction.
#}

{%- block page_body %}
{%- block settings_content %}{%- endblock settings_content %}
{%- endblock page_body %}

zenodo_accessrequests/templates/zenodo_accessrequests/settings/index.html
{#
## This file is part of Zenodo.
## Copyright (C) 2015, 2016 CERN.
##
## Zenodo is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## Zenodo is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Zenodo. If not, see <http://www.gnu.org/licenses/>.
##
## In applying this licence, CERN does not waive the privileges and immunities
## granted to it by virtue of its status as an Intergovernmental Organization
## or submit itself to any jurisdiction.
#}

{%- extends config.ACCESSREQUESTS_SETTINGS_TEMPLATE %}
{%- from "zenodo_accessrequests/_pagination.html" import render_pagination with context %}

{%- block settings_content %}
{%- set pending_num = requests.count() %}
<div class="panel-group panel-bot-margin">
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-edit fa-fw"></i>
      <strong>{{ _('Pending access requests') }}</strong>
      {%- if pending_num > 0 %}
      <span class="badge">{{pending_num}}</span>
      {%- endif %}
    </div>
      <ul class="list-group">
        {%- for r in requests %}
          {%- set record = get_record(r.recid)[1]  %}
          {%- set url = url_for('zenodo_accessrequests_settings.accessrequest', request_id=r.id) %}
          <li class="list-group-item">
            <div class="pull-right">
              <a href="{{url}}" class="btn btn-default btn-xs"><i class="fa fa-eye"></i> {{_('View')}}</a>
            </div>
            <a href="{{ url_for('zenodo_accessrequests_settings.accessrequest', request_id=r.id) }}">{{ record.get('title') }}</a><br/><small class="text-muted">{{_('Full name')}}: {{r.sender_full_name}}, {{_('Email')}}: {{r.sender_email}}, {{_('Justification')}}: {{r.justification|truncate(150)}}</small>
            </li>
          {%- else %}
            <li class="list-group-item">
            <p align="center"><em>{{ _('You have no pending access requests to accept/reject.') }}</em></p>
            <div class="row">
                <div class="col-md-12">
                    <p><strong>{{_('What\'s this?')}}</strong>
                    {%- trans sitename=config.THEME_SITENAME %}
                    There can be several reasons why a dataset cannot be shared openly (e.g. some clinical trial data). With {{sitename}}, you can now during upload set the access right to <span class="label label-danger">Restricted access</span>. This allows other users to request access to your dataset via {{sitename}}. Naturally, you are in full control of who gets granted/denied access.
                    {%- endtrans %}
                    </p>
                </div>

            </div>
            </li>
          {%- endfor %}
      </ul>
  </div>
</div>
<div class="panel-group panel-bot-margin">
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-share fa-fw"></i>
      <strong>{{ _('Shared links') }}</strong>
    </div>
    {%- if links_pagination.total > 0 or query %}
      <div class="panel-body">
        <div class="row">
          <div class="col-md-8">
            Shared links gives anyone with the link access to restricted files in embargoed/restricted/closed access uploads.
          </div>
          <div class="col-md-4">
            <form role="form" method="GET">
              <input name="sort" type="hidden" value="{{order.selected()}}">
              <div class="input-group">
                 <input autocomplete="off" name="query" class="form-control input-sm" type="text" tabindex="1" value="{{query}}">
                 <span class="input-group-btn">
                   <button type="submit" class="btn btn-primary btn-sm btn-inline-icon-hide-sm">
                     <i class="glyphicon glyphicon-search"></i> <span>Search</span>
                   </button>
                 </span>
              </div>
            </form>
          </div>
        </div>
      </div>


        <table class="table">
        <thead>
          <tr class="active">
            {% for t, f in [('Link','title'), ('Created','created'), ('Expires','expires_at'),] %}
            <td>
              <a href="{{ url_for('.index', query=query, sort=order.reverse(f)) }}"><strong>{{t}}</strong></a>
                {% if order.is_selected(f) %} <i class="fa fa-caret-{{order.dir(f, asc='up', desc='down')}}"></i>{% endif %}
            </td>
            {% endfor %}
            <td></td>
          </tr>
        </thead>
        <tbody>
          <tr>
          </tr>
          {%- for l in links_pagination.items %}
          {%- set url = l.get_absolute_url('invenio_records_ui.recid') %}
            <tr>
              <td class="col-md-6"><a href="{{url}}">{{l.title}}</a> <button data-clipboard-text="{{url}}" class="btn btn-default btn-xs clip-button"><i class="fa fa-copy" title="Copy link"></i> Copy</button> <br/><small class="text-muted">{{l.description|truncate(150)}}</small></td>
              <td class="col-md-2">{{l.created|tousertimezone|datetimeformat}}</td>
              <td class="col-md-2">{% if l.expires_at %}{{l.expires_at|dateformat}}{% endif %}</td>
              <td class="col-md-2">
                <form action="." method="POST">
                  {{form.csrf_token}}
                  {{form.link(value=l.id)}}
                  {{form.delete(class_="btn btn-danger btn-xs")}}
                </form>
              </td>
            </tr>
          {% else %}
          <tr>
            <td colspan="4"><div align="center"><em>Empty search result</em></div></td>
          </tr>
          {%- endfor %}
        </tbody>
        </table>

        {%- if links_pagination.pages > 1 %}
          <hr />
          <div align="center">
            {{ render_pagination(links_pagination, '.index') }}
          </div>
        {%- endif %}
        </div>

      {%- else %}
        <ul class="list-group">
          <li class="list-group-item">{{ _('Shared links gives anyone with the link access to restricted files in embargoed/restricted/closed access uploads.') }}</li>
        </ul>
      {%- endif %}
    </div>
  </div>
</div>
{%- endblock %}

zenodo_accessrequests/templates/zenodo_accessrequests/settings/request.html
{#
## This file is part of Zenodo.
## Copyright (C) 2015, 2016 CERN.
##
## Zenodo is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## Zenodo is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Zenodo. If not, see <http://www.gnu.org/licenses/>.
##
## In applying this licence, CERN does not waive the privileges and immunities
## granted to it by virtue of its status as an Intergovernmental Organization
## or submit itself to any jurisdiction.
#}

{%- extends config.ACCESSREQUESTS_SETTINGS_TEMPLATE %}

{%- block settings_content %}
{%- from "zenodo_accessrequests/_macro.html" import render_field with context %}
<div class="panel-group panel-bot-margin">
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-edit fa-fw"></i>
      <strong>{{ _('Pending access request') }}</strong>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <legend>Record</legend>
          <p><a href="{{ url_for('invenio_records_ui.recid', pid_value=accessrequest.recid) }}">{{ record['title'] }}</a> {% if "doi" in record %}<small class="text-muted">(DOI: {{record["doi"] }})</small>{% endif %}</p>

          {% if record.get('access_conditions') %}
            <h5>Conditions</h5>
            <p>{{ record["access_conditions"]|safe }}</p>
          {% endif %}
        </div>

        <div class="col-md-6">
          <legend>Decision</legend>
          <form action="." method="POST" role="form">
            {{form.csrf_token}}
            {{render_field(form.message)}}
            {{render_field(form.expires_at)}}

            <div class="center-block">
              {{form.accept(class_="btn btn-default")}}
              {{form.reject(class_="btn btn-default")}}
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <br />
          <div class="well">
            <legend>Request</legend>
            <dl>
              <dt>Full name</dt>
              <dd>{{accessrequest.sender_full_name}}</dd>
              <dt>Email address</dt>
              <dd><a href="mailto:{{accessrequest.sender_email}}">{{accessrequest.sender_email}}</a></dd>
              <dt>Jusitification</dt>
              <dd>{{accessrequest.justification|nl2br}}</dd>
            </dl>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}